package com.tools.objectManagement.entity;

import java.util.Date;

public class Account extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ACCOUNT_ID
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ACCOUNT_NAME
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.STATUS
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.CREATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.CREATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ACCOUNT_ID
     *
     * @return the value of account.ACCOUNT_ID
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ACCOUNT_ID
     *
     * @param accountId the value for account.ACCOUNT_ID
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ACCOUNT_NAME
     *
     * @return the value of account.ACCOUNT_NAME
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ACCOUNT_NAME
     *
     * @param accountName the value for account.ACCOUNT_NAME
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.STATUS
     *
     * @return the value of account.STATUS
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.STATUS
     *
     * @param status the value for account.STATUS
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.CREATED_DATE
     *
     * @return the value of account.CREATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.CREATED_DATE
     *
     * @param createdDate the value for account.CREATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.CREATED_BY
     *
     * @return the value of account.CREATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.CREATED_BY
     *
     * @param createdBy the value for account.CREATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.LAST_UPDATED_DATE
     *
     * @return the value of account.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for account.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.LAST_UPDATED_BY
     *
     * @return the value of account.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for account.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Aug 03 15:09:36 CST 2018
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}