package com.tools.objectManagement.entity;

import java.util.Date;


public class Location extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.LOCATION_ID
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.LOCATION_NAME
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.CREATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.CREATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.LAST_UPDATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.LAST_UPDATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.LOCATION_ID
     *
     * @return the value of location.LOCATION_ID
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.LOCATION_ID
     *
     * @param locationId the value for location.LOCATION_ID
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.LOCATION_NAME
     *
     * @return the value of location.LOCATION_NAME
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.LOCATION_NAME
     *
     * @param locationName the value for location.LOCATION_NAME
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.CREATED_DATE
     *
     * @return the value of location.CREATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.CREATED_DATE
     *
     * @param createdDate the value for location.CREATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.CREATED_BY
     *
     * @return the value of location.CREATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.CREATED_BY
     *
     * @param createdBy the value for location.CREATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.LAST_UPDATED_DATE
     *
     * @return the value of location.LAST_UPDATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for location.LAST_UPDATED_DATE
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.LAST_UPDATED_BY
     *
     * @return the value of location.LAST_UPDATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for location.LAST_UPDATED_BY
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}