package com.tools.objectManagement.entity;

import java.util.Date;

public class Vendor extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.VENDOR_ID
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private Integer vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.VENDOR_NAME
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private String vendorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.STATUS
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.CREATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.CREATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.LAST_UPDATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.LAST_UPDATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.VENDOR_ID
     *
     * @return the value of vendor.VENDOR_ID
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public Integer getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.VENDOR_ID
     *
     * @param vendorId the value for vendor.VENDOR_ID
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.VENDOR_NAME
     *
     * @return the value of vendor.VENDOR_NAME
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.VENDOR_NAME
     *
     * @param vendorName the value for vendor.VENDOR_NAME
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName == null ? null : vendorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.STATUS
     *
     * @return the value of vendor.STATUS
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.STATUS
     *
     * @param status the value for vendor.STATUS
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.CREATED_DATE
     *
     * @return the value of vendor.CREATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.CREATED_DATE
     *
     * @param createdDate the value for vendor.CREATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.CREATED_BY
     *
     * @return the value of vendor.CREATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.CREATED_BY
     *
     * @param createdBy the value for vendor.CREATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.LAST_UPDATED_DATE
     *
     * @return the value of vendor.LAST_UPDATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for vendor.LAST_UPDATED_DATE
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.LAST_UPDATED_BY
     *
     * @return the value of vendor.LAST_UPDATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for vendor.LAST_UPDATED_BY
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}