package com.tools.objectManagement.entity.mapper;

import com.tools.objectManagement.entity.Location;
import com.tools.objectManagement.entity.LocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper extends ObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    long countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int deleteByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int deleteByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    Location selectByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated Mon Jul 16 11:17:57 CST 2018
     */
    int updateByPrimaryKey(Location record);
}