package com.tools.objectManagement.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
//    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
//    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    int insert(Object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    int insertSelective(Object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    List<?> selectByExample(Object example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    List<?> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    Object selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
//    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
//    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    int updateByPrimaryKeySelective(Object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Thu Jun 28 16:17:11 CST 2018
     */
    int updateByPrimaryKey(Object record);
}