package com.tools.objectManagement.entity.mapper;

import com.tools.objectManagement.entity.Vendor;
import com.tools.objectManagement.entity.VendorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VendorMapper extends ObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    long countByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int deleteByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int deleteByPrimaryKey(Integer vendorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int insert(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int insertSelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    List<Vendor> selectByExample(VendorExample example);

    List<Vendor> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    Vendor selectByPrimaryKey(Integer vendorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int updateByExample(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int updateByPrimaryKeySelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbg.generated Thu Jun 28 16:30:44 CST 2018
     */
    int updateByPrimaryKey(Vendor record);
}