package com.tools.setup.entity;

import java.util.Date;

public class Field {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String fieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.FIELD_NAME
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.DESCRIPTION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.FIELD_TYPE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String fieldType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.LENGTH
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.DECIMAL_POSITION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Integer decimalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.FIELD_STATUS
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String fieldStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.FIELD_ID
     *
     * @return the value of field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.FIELD_ID
     *
     * @param fieldId the value for field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId == null ? null : fieldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.FIELD_NAME
     *
     * @return the value of field.FIELD_NAME
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.FIELD_NAME
     *
     * @param fieldName the value for field.FIELD_NAME
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.DESCRIPTION
     *
     * @return the value of field.DESCRIPTION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.DESCRIPTION
     *
     * @param description the value for field.DESCRIPTION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.FIELD_TYPE
     *
     * @return the value of field.FIELD_TYPE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.FIELD_TYPE
     *
     * @param fieldType the value for field.FIELD_TYPE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.LENGTH
     *
     * @return the value of field.LENGTH
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.LENGTH
     *
     * @param length the value for field.LENGTH
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.DECIMAL_POSITION
     *
     * @return the value of field.DECIMAL_POSITION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Integer getDecimalPosition() {
        return decimalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.DECIMAL_POSITION
     *
     * @param decimalPosition the value for field.DECIMAL_POSITION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setDecimalPosition(Integer decimalPosition) {
        this.decimalPosition = decimalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.FIELD_STATUS
     *
     * @return the value of field.FIELD_STATUS
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldStatus() {
        return fieldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.FIELD_STATUS
     *
     * @param fieldStatus the value for field.FIELD_STATUS
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldStatus(String fieldStatus) {
        this.fieldStatus = fieldStatus == null ? null : fieldStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.SOURCE
     *
     * @return the value of field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.SOURCE
     *
     * @param source the value for field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.CREATED_DATE
     *
     * @return the value of field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.CREATED_DATE
     *
     * @param createdDate the value for field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.CREATED_BY
     *
     * @return the value of field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.CREATED_BY
     *
     * @param createdBy the value for field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.LAST_UPDATED_DATE
     *
     * @return the value of field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.LAST_UPDATED_BY
     *
     * @return the value of field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}