package com.tools.setup.entity;

import java.util.Date;

import org.springframework.hateoas.ResourceSupport;

public class RecordField extends ResourceSupport {
	private Integer recordFieldId;
	
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column record_field.RECORD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   private String recordId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column record_field.FIELD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   private String fieldId;

	private String label;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.IS_PK
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String isPk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.IS_INDEX
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String isIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.IS_REQUIRED
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String isRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.IS_UNIQUE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String isUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String lastUpdatedBy;

    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column field.FIELD_TYPE
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   private String fieldType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column field.LENGTH
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   private Integer length;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column field.DECIMAL_POSITION
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   private Integer decimalPosition;
   
	public Integer getRecordFieldId() {
		return recordFieldId;
	}

	public void setRecordFieldId(Integer recordFieldId) {
		this.recordFieldId = recordFieldId;
	}
	
   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column record_field.RECORD_ID
    *
    * @return the value of record_field.RECORD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   public String getRecordId() {
       return recordId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column record_field.RECORD_ID
    *
    * @param recordId the value for record_field.RECORD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   public void setRecordId(String recordId) {
       this.recordId = recordId == null ? null : recordId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column record_field.FIELD_ID
    *
    * @return the value of record_field.FIELD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   public String getFieldId() {
       return fieldId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column record_field.FIELD_ID
    *
    * @param fieldId the value for record_field.FIELD_ID
    *
    * @mbg.generated Fri Jun 22 14:44:25 CST 2018
    */
   public void setFieldId(String fieldId) {
       this.fieldId = fieldId == null ? null : fieldId.trim();
   }
   
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.IS_PK
     *
     * @return the value of record_field.IS_PK
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getIsPk() {
        return isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.IS_PK
     *
     * @param isPk the value for record_field.IS_PK
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setIsPk(String isPk) {
        this.isPk = isPk == null ? null : isPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.IS_INDEX
     *
     * @return the value of record_field.IS_INDEX
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getIsIndex() {
        return isIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.IS_INDEX
     *
     * @param isIndex the value for record_field.IS_INDEX
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setIsIndex(String isIndex) {
        this.isIndex = isIndex == null ? null : isIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.IS_REQUIRED
     *
     * @return the value of record_field.IS_REQUIRED
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.IS_REQUIRED
     *
     * @param isRequired the value for record_field.IS_REQUIRED
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired == null ? null : isRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.IS_UNIQUE
     *
     * @return the value of record_field.IS_UNIQUE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getIsUnique() {
        return isUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.IS_UNIQUE
     *
     * @param isUnique the value for record_field.IS_UNIQUE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setIsUnique(String isUnique) {
        this.isUnique = isUnique == null ? null : isUnique.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.SOURCE
     *
     * @return the value of record_field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.SOURCE
     *
     * @param source the value for record_field.SOURCE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.CREATED_DATE
     *
     * @return the value of record_field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.CREATED_DATE
     *
     * @param createdDate the value for record_field.CREATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.CREATED_BY
     *
     * @return the value of record_field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.CREATED_BY
     *
     * @param createdBy the value for record_field.CREATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.LAST_UPDATED_DATE
     *
     * @return the value of record_field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for record_field.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.LAST_UPDATED_BY
     *
     * @return the value of record_field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for record_field.LAST_UPDATED_BY
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.FIELD_TYPE
     *
     * @return the value of field.FIELD_TYPE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.FIELD_TYPE
     *
     * @param fieldType the value for field.FIELD_TYPE
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.LENGTH
     *
     * @return the value of field.LENGTH
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.LENGTH
     *
     * @param length the value for field.LENGTH
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.DECIMAL_POSITION
     *
     * @return the value of field.DECIMAL_POSITION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public Integer getDecimalPosition() {
        return decimalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.DECIMAL_POSITION
     *
     * @param decimalPosition the value for field.DECIMAL_POSITION
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setDecimalPosition(Integer decimalPosition) {
        this.decimalPosition = decimalPosition;
    }
    
}