package com.tools.setup.entity;

public class RecordFieldKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.RECORD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    private String fieldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.RECORD_ID
     *
     * @return the value of record_field.RECORD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.RECORD_ID
     *
     * @param recordId the value for record_field.RECORD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_field.FIELD_ID
     *
     * @return the value of record_field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_field.FIELD_ID
     *
     * @param fieldId the value for record_field.FIELD_ID
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId == null ? null : fieldId.trim();
    }
}