hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    setup-service:
        path: /setup/**
        url: http://setup-service:5000
        stripPrefix: false
        sensitiveHeaders:

    object-service:
        path: /object/**
        url: http://object-service:6000
        stripPrefix: false
        sensitiveHeaders:



server:
  port: 80
