spring:
  datasource:
    url: jdbc:mysql://slc15din.us.oracle.com:3306/userdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springuser
    password: Passw0rd1!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.tools.setup.entity
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    context-path: /setup
  port: 5000
