package com.tools.setup.dao;

import com.tools.setup.entity.Field;
import com.tools.setup.entity.FieldExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    long countByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByPrimaryKey(String fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insert(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insertSelective(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    List<Field> selectByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    Field selectByPrimaryKey(String fieldId);

    List<Field> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Field record, @Param("example") FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExample(@Param("record") Field record, @Param("example") FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKeySelective(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKey(Field record);
}