package com.tools.setup.dao;

import com.tools.setup.entity.Record;
import com.tools.setup.entity.RecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    long countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    List<Record> selectByExample(RecordExample example);
    
    List<Record> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    Record selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKey(Record record);
    
}