package com.tools.setup.dao;

import com.tools.setup.entity.RecordField;
import com.tools.setup.entity.RecordFieldExample;
import com.tools.setup.entity.RecordFieldKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordFieldDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    long countByExample(RecordFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByExample(RecordFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insert(RecordField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int insertSelective(RecordField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    List<RecordField> selectByExample(RecordFieldExample example);
    
    List<RecordField> selectAll();

    List<RecordField> selectByRecordId(String recordId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    RecordField selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") RecordField record, @Param("example") RecordFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByExample(@Param("record") RecordField record, @Param("example") RecordFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKeySelective(RecordField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_field
     *
     * @mbg.generated Fri Jun 22 14:44:25 CST 2018
     */
    int updateByPrimaryKey(RecordField record);
}