logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:3000/uaa/users/current
      
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: slc15din.us.oracle.com
    port: 6379
  cloud: 
    bus: 
      enabled: true
      trace: 
        enabled: true
management:
  endpoints: 
    web: 
      exposure:
        include: bus-refresh    