hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
        path: /uaa/**
        url: http://127.0.0.1:3000
        serviceId: auth-service
        stripPrefix: false
        sensitiveHeaders:  
    setup-service:
        path: /setup/**
        url: http://127.0.0.1:5000
        serviceId: setup-service
        stripPrefix: false
        sensitiveHeaders:

    object-service:
        path: /object/**
        url: http://127.0.0.1:6000
        serviceId: object-service
        stripPrefix: false
        sensitiveHeaders:



server:
  port: 4000
