security:
  oauth2:
    client:
      clientId: object-service
      clientSecret: ${OBJECT_SERVICE_PASSWORD}
      accessTokenUri: http://127.0.0.1:3000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
      
spring:
  datasource:
    url: jdbc:mysql://slc15din.us.oracle.com:3306/userdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springuser
    password: Passw0rd1!
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.tools.objectManagement.entity
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    context-path: /object
  port: 6000